In [1]:
import numpy as np
import pandas as pd

In [ ]:
fruits = pd.DataFrame({"Apples" : [30] , "Bananas" : [21]})
fruits

   Apples  Bananas
0      30       21

In [ ]:
fruit_sales =pd.DataFrame({"Apples" : [35,41] , "Bananas" : [21,34]}, index=['2017 Sales' , '2018 Sales'])
fruit_sales

            Apples  Bananas
2017 Sales      35       21
2018 Sales      41       34

In [ ]:
ingredients = pd.Series(["4 cups","1 cup","2 large","1 can"],index=["Flour","Milk","Eggs","Spam"],name="Dinner")
ingredients

Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can
Name: Dinner, dtype: object

In [ ]:
animals = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
animals

        Cows  Goats
Year 1    12     22
Year 2    20     19

In [ ]:
data = animals.to_csv('cows_and_goats.csv')
data

In [ ]:
from google.colab import drive
drive.mount("/content/gdrive")
data = pd.read_csv("/content/gdrive/My Drive/Sample data/winemag-data-130k-v2.csv", index_col=0)
df = pd.DataFrame(data)

Mounted at /content/gdrive

In [ ]:
df

         country  ...                                    winery
0          Italy  ...                                   Nicosia
1       Portugal  ...                       Quinta dos Avidagos
2             US  ...                                 Rainstorm
3             US  ...                                St. Julian
4             US  ...                              Sweet Cheeks
...          ...  ...                                       ...
129966   Germany  ...  Dr. H. Thanisch (Erben Müller-Burggraef)
129967        US  ...                                  Citation
129968    France  ...                           Domaine Gresser
129969    France  ...                      Domaine Marcel Deiss
129970    France  ...                          Domaine Schoffit

[129971 rows x 13 columns]

In [ ]:
df.country
# or df["country"]

0            Italy
1         Portugal
2               US
3               US
4               US
            ...
129966     Germany
129967          US
129968      France
129969      France
129970      France
Name: country, Length: 129971, dtype: object

In [ ]:
df["country"][0]

'Italy'

INDEXING IN PANDAS

In [ ]:
df.iloc[0]

country                                                              Italy
description              Aromas include tropical fruit, broom, brimston...
designation                                                   Vulkà Bianco
points                                                                  87
price                                                                  NaN
province                                                 Sicily & Sardinia
region_1                                                              Etna
region_2                                                               NaN
taster_name                                                  Kerin O’Keefe
taster_twitter_handle                                         @kerinokeefe
title                                    Nicosia 2013 Vulkà Bianco  (Etna)
variety                                                        White Blend
winery                                                             Nicosia
Name: 0, dtype: object

In [ ]:
df.iloc[:,0]

0            Italy
1         Portugal
2               US
3               US
4               US
            ...
129966     Germany
129967          US
129968      France
129969      France
129970      France
Name: country, Length: 129971, dtype: object

In [ ]:
df.iloc[:3,0]

0       Italy
1    Portugal
2          US
Name: country, dtype: object

In [ ]:
df.iloc[1:3,0]

1    Portugal
2          US
Name: country, dtype: object

In [ ]:
df.iloc[[1,2,3],0]

1    Portugal
2          US
3          US
Name: country, dtype: object

In [ ]:
df.iloc[-5:]

        country  ...                                    winery
129966  Germany  ...  Dr. H. Thanisch (Erben Müller-Burggraef)
129967       US  ...                                  Citation
129968   France  ...                           Domaine Gresser
129969   France  ...                      Domaine Marcel Deiss
129970   France  ...                          Domaine Schoffit

[5 rows x 13 columns]

In [ ]:
df.loc[0, 'country']

'Italy'

In [ ]:
df.loc[:, ['taster_name', 'taster_twitter_handle', 'points']]

               taster_name taster_twitter_handle  points
0            Kerin O’Keefe          @kerinokeefe      87
1               Roger Voss            @vossroger      87
2             Paul Gregutt           @paulgwine       87
3       Alexander Peartree                   NaN      87
4             Paul Gregutt           @paulgwine       87
...                    ...                   ...     ...
129966  Anna Lee C. Iijima                   NaN      90
129967        Paul Gregutt           @paulgwine       90
129968          Roger Voss            @vossroger      90
129969          Roger Voss            @vossroger      90
129970          Roger Voss            @vossroger      90

[129971 rows x 3 columns]

MANIPULATING THE INDEX

In [ ]:
df.set_index("title")

                                                     country  ...                                    winery
title                                                         ...
Nicosia 2013 Vulkà Bianco  (Etna)                      Italy  ...                                   Nicosia
Quinta dos Avidagos 2011 Avidagos Red (Douro)       Portugal  ...                       Quinta dos Avidagos
Rainstorm 2013 Pinot Gris (Willamette Valley)             US  ...                                 Rainstorm
St. Julian 2013 Reserve Late Harvest Riesling (...        US  ...                                St. Julian
Sweet Cheeks 2012 Vintner's Reserve Wild Child ...        US  ...                              Sweet Cheeks
...                                                      ...  ...                                       ...
Dr. H. Thanisch (Erben Müller-Burggraef) 2013 B...   Germany  ...  Dr. H. Thanisch (Erben Müller-Burggraef)
Citation 2004 Pinot Noir (Oregon)                         US  ...                                  Citation
Domaine Gresser 2013 Kritt Gewurztraminer (Alsace)    France  ...                           Domaine Gresser
Domaine Marcel Deiss 2012 Pinot Gris (Alsace)         France  ...                      Domaine Marcel Deiss
Domaine Schoffit 2012 Lieu-dit Harth Cuvée Caro...    France  ...                          Domaine Schoffit

[129971 rows x 12 columns]

CONDITIONAL SELECTION

In [ ]:
df.country == 'Italy'

0          True
1         False
2         False
3         False
4         False
          ...
129966    False
129967    False
129968    False
129969    False
129970    False
Name: country, Length: 129971, dtype: bool

In [ ]:
df.loc[df.country == 'Italy']

       country  ...                           winery
0        Italy  ...                          Nicosia
6        Italy  ...                  Terre di Giurfo
13       Italy  ...              Masseria Setteporte
22       Italy  ...               Baglio di Pianetto
24       Italy  ...                        Canicattì
...        ...  ...                              ...
129929   Italy  ...             Col Vetoraz Spumanti
129943   Italy  ...  Baglio del Cristo di Campobello
129947   Italy  ...         Feudo Principi di Butera
129961   Italy  ...                              COS
129962   Italy  ...                         Cusumano

[19540 rows x 13 columns]

In [ ]:
df.loc[(df.country == 'Italy') & (df.points >= 90)]

       country  ...                           winery
120      Italy  ...                          Ceretto
130      Italy  ...                          Ceretto
133      Italy  ...             Poderi Luigi Einaudi
135      Italy  ...                  Giacomo Ascheri
140      Italy  ...                     Poderi Colla
...        ...  ...                              ...
129929   Italy  ...             Col Vetoraz Spumanti
129943   Italy  ...  Baglio del Cristo di Campobello
129947   Italy  ...         Feudo Principi di Butera
129961   Italy  ...                              COS
129962   Italy  ...                         Cusumano

[6648 rows x 13 columns]

In [ ]:
df.loc[(df.country == 'Italy') | (df.points >= 90)]

        country  ...                                    winery
0         Italy  ...                                   Nicosia
6         Italy  ...                           Terre di Giurfo
13        Italy  ...                       Masseria Setteporte
22        Italy  ...                        Baglio di Pianetto
24        Italy  ...                                 Canicattì
...         ...  ...                                       ...
129966  Germany  ...  Dr. H. Thanisch (Erben Müller-Burggraef)
129967       US  ...                                  Citation
129968   France  ...                           Domaine Gresser
129969   France  ...                      Domaine Marcel Deiss
129970   France  ...                          Domaine Schoffit

[61937 rows x 13 columns]

In [ ]:
df.loc[df.country.isin(['Italy', 'France'])]

       country  ...                   winery
0        Italy  ...                  Nicosia
6        Italy  ...          Terre di Giurfo
7       France  ...                 Trimbach
9       France  ...       Jean-Baptiste Adam
11      France  ...               Leon Beyer
...        ...  ...                      ...
129964  France  ...          Domaine Ehrhart
129965  France  ...  Domaine Rieflé-Landmann
129968  France  ...          Domaine Gresser
129969  France  ...     Domaine Marcel Deiss
129970  France  ...         Domaine Schoffit

[41633 rows x 13 columns]

In [ ]:
df.loc[df.price.notnull()]

         country  ...                                    winery
1       Portugal  ...                       Quinta dos Avidagos
2             US  ...                                 Rainstorm
3             US  ...                                St. Julian
4             US  ...                              Sweet Cheeks
5          Spain  ...                                    Tandem
...          ...  ...                                       ...
129966   Germany  ...  Dr. H. Thanisch (Erben Müller-Burggraef)
129967        US  ...                                  Citation
129968    France  ...                           Domaine Gresser
129969    France  ...                      Domaine Marcel Deiss
129970    France  ...                          Domaine Schoffit

[120975 rows x 13 columns]

In [ ]:
df['critic'] = 'everyone'
df['critic']

0         everyone
1         everyone
2         everyone
3         everyone
4         everyone
            ...
129966    everyone
129967    everyone
129968    everyone
129969    everyone
129970    everyone
Name: critic, Length: 129971, dtype: object

In [ ]:
df['index_backwards'] = range(len(df), 0, -1)
df['index_backwards']

0         129971
1         129970
2         129969
3         129968
4         129967
           ...
129966         5
129967         4
129968         3
129969         2
129970         1
Name: index_backwards, Length: 129971, dtype: int64

SUMMARY FUNCTIONS

In [ ]:
df.describe()

              points          price  index_backwards
count  129971.000000  120975.000000    129971.000000
mean       88.447138      35.363389     64986.000000
std         3.039730      41.022218     37519.540256
min        80.000000       4.000000         1.000000
25%        86.000000      17.000000     32493.500000
50%        88.000000      25.000000     64986.000000
75%        91.000000      42.000000     97478.500000
max       100.000000    3300.000000    129971.000000

In [ ]:
df.points.mean()

88.44713820775404

In [ ]:
df.taster_name.value_counts()

Roger Voss            25514
Michael Schachner     15134
Kerin O’Keefe         10776
Virginie Boone         9537
Paul Gregutt           9532
Matt Kettmann          6332
Joe Czerwinski         5147
Sean P. Sullivan       4966
Anna Lee C. Iijima     4415
Jim Gordon             4177
Anne Krebiehl MW       3685
Lauren Buzzeo          1835
Susan Kostrzewa        1085
Mike DeSimone           514
Jeff Jenssen            491
Alexander Peartree      415
Carrie Dykes            139
Fiona Adams              27
Christina Pickard         6
Name: taster_name, dtype: int64

MAPS

In [ ]:
df_points_mean = df.points.mean()
df.points.map(lambda p : p - df_points_mean)

0        -1.447138
1        -1.447138
2        -1.447138
3        -1.447138
4        -1.447138
            ...
129966    1.552862
129967    1.552862
129968    1.552862
129969    1.552862
129970    1.552862
Name: points, Length: 129971, dtype: float64

In [ ]:
df.country + " - " + df.region_1

0                     Italy - Etna
1                              NaN
2           US - Willamette Valley
3         US - Lake Michigan Shore
4           US - Willamette Valley
                    ...
129966                         NaN
129967                 US - Oregon
129968             France - Alsace
129969             France - Alsace
129970             France - Alsace
Length: 129971, dtype: object